const ALBA_SUPABASE_URL="https://xuilkvsehlnkqtlfkblw.supabase.co";
const ALBA_SUPABASE_KEY="sb_publishable_Mdr55DRXLuqCXIYjh5hepQ_Lx3T3-Pg";

document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id);
 const grid=$('newsGrid'),featured=$('featuredNews'),filters=$('categoryFilters'),sourceFilters=$('sourceFilters'),sectionLinks=$('sectionLinks'),input=$('searchInput'),empty=$('emptyState'),liveStatus=$('liveStatus'),newsCount=$('newsCount'),lastUpdated=$('lastUpdated');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clean=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
 const normalizeTitle=v=>clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
 const image=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
 const fallback=(cat='Actualidad')=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 675"><rect width="1200" height="675" fill="#07111f"/><text x="65" y="120" fill="#16c7f2" font-size="28" font-family="Arial">ALBA · NOTICIAS</text><text x="65" y="370" fill="white" font-size="76" font-weight="700" font-family="Arial">${esc(cat)}</text></svg>`)}`;
 const date=v=>v?new Date(v).toLocaleString('es-HN',{dateStyle:'medium',timeStyle:'short'}):'';
 const get=async(path,attempt=0)=>{const c=new AbortController();const timer=setTimeout(()=>c.abort(),12000);try{const r=await fetch(`${ALBA_SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:ALBA_SUPABASE_KEY,Authorization:`Bearer ${ALBA_SUPABASE_KEY}`,Accept:'application/json'},cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`Supabase HTTP ${r.status}`);return await r.json()}catch(e){if(attempt<1)return get(path,attempt+1);throw e}finally{clearTimeout(timer)}};
 let news=[],activeCategory='Todas',activeSource='Todas';
 const uniqueNews=rows=>{const seen=new Set(),urls=new Set();return [...rows].sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).filter(n=>{const t=normalizeTitle(n.title),u=clean(n.canonical_url||'').toLowerCase().split('#')[0];if((t&&seen.has(t))||(u&&urls.has(u)))return false;if(t)seen.add(t);if(u)urls.add(u);return true})};
 const analysis=n=>{const m=n.metadata&&typeof n.metadata==='object'?n.metadata:{};const d=m.alba_analysis_data&&typeof m.alba_analysis_data==='object'?m.alba_analysis_data:{};return {summary:clean(m.alba_summary||m.alba_resumen||d.summary||n.summary||n.title),what:clean(m.alba_what_happened||d.what_happened||''),analysis:clean(m.alba_analysis||d.analysis||'ALBA analiza los hechos confirmados y su contexto.'),impact:clean(m.alba_impact||m.alba_impacto||d.impact||'El impacto dependerá de cómo evolucione la situación.'),next:clean(m.alba_what_next||m.alba_que_sigue||d.what_next||'ALBA seguirá el desarrollo de este tema.'),points:Array.isArray(m.alba_key_points)?m.alba_key_points:Array.isArray(d.key_points)?d.key_points:[]}};
 const summary=n=>{const i=analysis(n),base=i.summary,extra=i.what;if(!extra||normalizeTitle(extra)===normalizeTitle(base))return base;const text=`${base} ${extra}`.trim();return text.length>620?text.slice(0,617).trimEnd()+'…':text};
 const related=n=>{const tokens=new Set(normalizeTitle(`${n.title} ${n.category}`).split(' ').filter(x=>x.length>4));return news.filter(x=>x.id!==n.id).map(x=>{const words=normalizeTitle(`${x.title} ${x.category}`).split(' ');let score=x.category===n.category?2:0;words.forEach(w=>{if(tokens.has(w))score++});return {x,score}}).filter(a=>a.score>=3).sort((a,b)=>b.score-a.score||new Date(b.x.published_at||0)-new Date(a.x.published_at||0)).slice(0,3).map(a=>a.x)};
 const open=n=>{let modal=$('articleModal');if(!modal){modal=document.createElement('div');modal.id='articleModal';modal.className='article-modal';modal.innerHTML='<div class="article-modal-backdrop"></div><article class="article-view"><button class="article-close" type="button">×</button><div id="articleModalImage" class="article-view-image"></div><div class="article-view-content"><div id="articleModalMeta" class="card-meta"></div><h2 id="articleModalTitle"></h2><div id="articleModalDate" class="article-view-date"></div><section><div class="insight-label">RESUMEN ALBA</div><p id="articleModalSummary"></p></section><section class="insight-box"><div class="insight-label">¿QUÉ PASÓ?</div><p id="articleModalWhat"></p></section><section class="insight-box"><div class="insight-label">ANÁLISIS ALBA</div><p id="articleModalAnalysis"></p></section><section class="key-points-box"><div class="insight-label">PUNTOS CLAVE</div><ul id="articleModalPoints"></ul></section><section class="impact-box"><div class="insight-label">¿CÓMO BENEFICIA O AFECTA?</div><p id="articleModalImpact"></p></section><section class="next-box"><div class="insight-label">¿QUÉ SIGUE?</div><p id="articleModalNext"></p></section><section class="related-box"><div class="insight-label">TAMBIÉN TE PUEDE INTERESAR</div><div id="articleRelated" class="related-list"></div></section><div class="article-source-note">Fuente consultada: <strong id="articleModalSource"></strong><br>ALBA · Noticias · Contexto · Análisis</div></div></article>';document.body.appendChild(modal);modal.querySelector('.article-close').onclick=()=>{modal.classList.remove('open');document.body.classList.remove('modal-open')};modal.querySelector('.article-modal-backdrop').onclick=()=>{modal.classList.remove('open');document.body.classList.remove('modal-open')}}
 const i=analysis(n);$('articleModalTitle').textContent=n.title;$('articleModalDate').textContent=date(n.published_at);$('articleModalSummary').textContent=summary(n);$('articleModalWhat').textContent=i.what||'La información disponible indica los hechos señalados en la noticia.';$('articleModalAnalysis').textContent=i.analysis;$('articleModalImpact').textContent=i.impact;$('articleModalNext').textContent=i.next;$('articleModalSource').textContent=n.source;$('articleModalMeta').innerHTML=`<span class="tag">${esc(n.category)}</span><span class="source-tag">${esc(n.source)}</span>`;$('articleModalPoints').innerHTML=i.points.length?i.points.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>Información clave en seguimiento.</li>' ;const rel=related(n);$('articleRelated').innerHTML=rel.length?rel.map(x=>`<button type="button" class="related-item" data-id="${esc(x.id)}"><strong>${esc(x.title)}</strong><small>${esc(x.source)} · ${esc(date(x.published_at))}</small></button>`).join(''):'<p class="related-empty">No hay historias relacionadas suficientes todavía.</p>';$('articleModalImage').innerHTML=`<img src="${esc(image(n.image_url)||fallback(n.category))}" alt="${esc(n.title)}">`;modal.classList.add('open');document.body.classList.add('modal-open');modal.querySelectorAll('.related-item').forEach(b=>b.onclick=()=>{const x=news.find(a=>a.id===b.dataset.id);if(x)open(x)})};
 const render=()=>{const q=(input?.value||'').trim().toLowerCase();const items=news.filter(n=>(activeCategory==='Todas'||n.category===activeCategory)&&(activeSource==='Todas'||n.source===activeSource)&&`${n.title} ${n.summary||''} ${n.category} ${n.source}`.toLowerCase().includes(q));if(newsCount)newsCount.textContent=`${items.length} noticias disponibles`;if(empty)empty.hidden=items.length>0;if(featured){const n=items[0];featured.innerHTML=n?`<article class="featured"><button class="featured-media article-open" data-id="${n.id}" type="button"><img src="${esc(image(n.image_url)||fallback(n.category))}" alt="${esc(n.title)}"></button><div class="featured-content"><div class="card-meta"><span class="tag">${esc(n.category)}</span><span class="source-tag">${esc(n.source)}</span></div><h2>${esc(n.title)}</h2><p>${esc(summary(n))}</p><div class="featured-meta">${esc(date(n.published_at))}</div><button class="featured-link article-open" data-id="${n.id}" type="button">Leer análisis ALBA →</button></div></article>`:''}if(grid)grid.innerHTML=items.slice(1).map(n=>`<article class="card"><button class="card-image-wrap article-open" data-id="${n.id}" type="button"><img class="card-image" src="${esc(image(n.image_url)||fallback(n.category))}" alt="${esc(n.title)}" loading="lazy"></button><div class="card-body"><div class="card-meta"><span class="tag">${esc(n.category)}</span><span class="source-tag">${esc(n.source)}</span></div><h3>${esc(n.title)}</h3><p>${esc(summary(n))}</p><div class="card-footer"><time>${esc(date(n.published_at))}</time><button class="read-more article-open" data-id="${n.id}" type="button">Ver análisis →</button></div></div></article>`).join('');document.querySelectorAll('.article-open').forEach(b=>b.onclick=()=>{const n=news.find(x=>x.id===b.dataset.id);if(n)open(n)});renderSections()};
 const renderSections=()=>{if(!sectionLinks)return;const cats=['Honduras','Internacional','Política','Economía','Deportes','Salud','Tecnología','Ciencia','Clima','Tendencias'];sectionLinks.innerHTML=cats.map(c=>`<button class="section-link" type="button" data-cat="${esc(c)}"><strong>${esc(c)}</strong><small>${news.filter(n=>n.category===c).length} noticias</small></button>`).join('');sectionLinks.querySelectorAll('.section-link').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;render();document.getElementById('noticias')?.scrollIntoView({behavior:'smooth'})})};
 const renderFilters=()=>{if(filters)filters.innerHTML=['Todas',...new Set(news.map(n=>n.category))].map(c=>`<button type="button" class="filter ${c==='Todas'?'active':''}" data-value="${esc(c)}">${esc(c)}</button>`).join('');if(sourceFilters)sourceFilters.innerHTML=['Todas',...new Set(news.map(n=>n.source))].map(s=>`<button type="button" class="filter ${s==='Todas'?'active':''}" data-value="${esc(s)}">${esc(s)}</button>`).join('');[filters,sourceFilters].forEach(box=>box?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;if(box===filters)activeCategory=b.dataset.value;else activeSource=b.dataset.value;box.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}))};
 const load=async()=>{try{if(liveStatus)liveStatus.textContent='Conectando con ALBA…';const results=await Promise.allSettled([get('articles?select=id,title,summary,published_at,image_url,canonical_url,category_id,source_id,metadata&status=eq.published&order=published_at.desc&limit=500'),get('categories?select=id,name&is_active=eq.true'),get('sources?select=id,name&is_active=eq.true')]);if(results[0].status!=='fulfilled')throw results[0].reason;const cats=results[1].status==='fulfilled'?results[1].value:[];const sources=results[2].status==='fulfilled'?results[2].value:[];const cm=Object.fromEntries(cats.map(x=>[x.id,x.name])),sm=Object.fromEntries(sources.map(x=>[x.id,x.name]));news=uniqueNews(results[0].value.map(n=>({...n,category:cm[n.category_id]||'Actualidad',source:sm[n.source_id]||'Fuente'})));renderFilters();render();if(liveStatus)liveStatus.textContent=`Actualidad conectada · ${news.length} historias únicas`;if(lastUpdated)lastUpdated.textContent='Última actualización: '+new Date().toLocaleTimeString('es-HN')}catch(e){console.error('ALBA load:',e);if(liveStatus)liveStatus.textContent='Error de conexión con las noticias';if(newsCount)newsCount.textContent='No se pudo actualizar';if(empty){empty.hidden=false;empty.textContent='No se pudo conectar con ALBA. Intenta actualizar la página.'}}};
 if($('year'))$('year').textContent=new Date().getFullYear();input?.addEventListener('input',render);document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.article-modal.open')?.classList.remove('open');document.body.classList.remove('modal-open')}});load();setInterval(load,900000);
});