const ALBA_SUPABASE_URL="https://xuilkvsehlnkqtlfkblw.supabase.co";
const ALBA_SUPABASE_KEY="sb_publishable_Mdr55DRXLuqCXIYjh5hepQ_Lx3T3-Pg";

document.addEventListener('DOMContentLoaded',()=>{
 const year=document.getElementById('year'); if(year)year.textContent=new Date().getFullYear();
 const grid=document.getElementById('newsGrid'),featured=document.getElementById('featuredNews'),filters=document.getElementById('categoryFilters'),sourceFilters=document.getElementById('sourceFilters'),input=document.getElementById('searchInput'),empty=document.getElementById('emptyState'),searchBar=document.getElementById('searchBar');
 const liveStatus=document.getElementById('liveStatus'),newsCount=document.getElementById('newsCount'),lastUpdated=document.getElementById('lastUpdated');
 let activeCategory='Todas',activeSource='Todas',news=[],categories=[],sources=[];
 const fallbackCategories=['Honduras','Internacional','Política','Economía','Deportes','Salud','Tecnología','Ciencia','Clima','Tendencias'];
 const fallbackSources=['El Heraldo Honduras','Tu Nota Honduras','BBC Mundo','BBC News World','EL PAÍS'];
 const escapeHtml=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeImage=(v='')=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
 const formatDate=v=>v?new Date(v).toLocaleString('es-HN',{dateStyle:'medium',timeStyle:'short'}):'';
 const cleanText=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
 const albaInsights=n=>{
   const meta=n.metadata&&typeof n.metadata==='object'?n.metadata:{};
   const base=cleanText(n.summary||n.title); const words=base.split(/\s+/).slice(0,55).join(' ');
   const customSummary=meta.alba_summary||meta.alba_resumen, customAnalysis=meta.alba_analysis||meta.alba_analisis, customImpact=meta.alba_impact||meta.alba_impacto, customNext=meta.alba_what_next||meta.alba_que_sigue;
   const summary=customSummary||`ALBA resume esta información a partir de los datos disponibles: ${words}${base.split(/\s+/).length>55?'…':''}`;
   const analysis=customAnalysis||`El punto central de esta noticia es su posible impacto en ${n.category==='Honduras'?'Honduras y la vida cotidiana de la población':'la evolución de la situación y las decisiones que puedan tomarse a partir de ella'}. ALBA distingue los hechos disponibles de las interpretaciones y evita presentar como confirmado aquello que todavía requiere verificación.`;
   const impact=customImpact||`El efecto para la población dependerá de cómo evolucione el hecho y de las decisiones que se adopten. ALBA identifica aquí las posibles consecuencias sociales, económicas o institucionales, sin afirmar resultados que aún no estén confirmados.`;
   const whatNext=customNext||`ALBA seguirá el desarrollo de este tema. Las próximas declaraciones, decisiones oficiales y nuevos datos permitirán determinar con mayor precisión qué consecuencias tendrá.`;
   return {summary,analysis,impact,whatNext};
 };
 const ensureModal=()=>{if(document.getElementById('articleModal'))return;const m=document.createElement('div');m.id='articleModal';m.className='article-modal';m.innerHTML=`<div class="article-modal-backdrop" data-close-article></div><article class="article-view" role="dialog" aria-modal="true" aria-labelledby="articleModalTitle"><button class="article-close" type="button" aria-label="Cerrar noticia" data-close-article>×</button><div id="articleModalImage" class="article-view-image"></div><div class="article-view-content"><div id="articleModalMeta" class="card-meta"></div><h2 id="articleModalTitle"></h2><div id="articleModalDate" class="article-view-date"></div><section><div class="insight-label">RESUMEN ALBA</div><p id="articleModalSummary"></p></section><section class="insight-box"><div class="insight-label">ANÁLISIS ALBA</div><p id="articleModalAnalysis"></p></section><section class="impact-box"><div class="insight-label">¿CÓMO BENEFICIA O AFECTA?</div><p id="articleModalImpact"></p></section><section class="next-box"><div class="insight-label">¿QUÉ SIGUE?</div><p id="articleModalNext"></p></section><div class="article-source-note">Fuente consultada: <strong id="articleModalSource"></strong><br>ALBA transforma la información disponible en resumen, contexto y análisis propio. Esta vista no reproduce íntegramente el contenido de la fuente.</div><div class="article-source-note">ALBA · Noticias · Contexto · Análisis</div></div></article>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target.closest('[data-close-article]'))closeArticle()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeArticle()})};
 const closeArticle=()=>{const m=document.getElementById('articleModal');if(m){m.classList.remove('open');document.body.classList.remove('modal-open')}};
 const openArticle=n=>{ensureModal();const m=document.getElementById('articleModal'),ins=albaInsights(n),img=safeImage(n.image_url),meta=document.getElementById('articleModalMeta');document.getElementById('articleModalTitle').textContent=n.title;document.getElementById('articleModalDate').textContent=formatDate(n.published_at);document.getElementById('articleModalSummary').textContent=ins.summary;document.getElementById('articleModalAnalysis').textContent=ins.analysis;document.getElementById('articleModalImpact').textContent=ins.impact;document.getElementById('articleModalNext').textContent=ins.whatNext;document.getElementById('articleModalSource').textContent=n.source;meta.innerHTML=`<span class="tag">${escapeHtml(n.category)}</span><span class="source-tag">${escapeHtml(n.source)}</span>`;const im=document.getElementById('articleModalImage');im.innerHTML=img?`<img src="${escapeHtml(img)}" alt="${escapeHtml(n.title)}">`:'<div class="featured-placeholder">ALBA · NOTICIAS</div>';m.classList.add('open');document.body.classList.add('modal-open');document.querySelector('.article-close')?.focus()};
 const render=()=>{
  const q=(input?.value||'').trim().toLowerCase();
  const items=news.filter(n=>{const text=`${n.title} ${n.summary||''} ${n.category} ${n.source}`.toLowerCase();return (activeCategory==='Todas'||n.category===activeCategory)&&(activeSource==='Todas'||n.source===activeSource)&&text.includes(q)});
  if(newsCount)newsCount.textContent=`${items.length} noticias disponibles`;
  if(featured){const lead=items[0];featured.innerHTML=lead?`<article class="featured"><button class="featured-media article-open" data-id="${escapeHtml(lead.id)}" type="button" aria-label="Abrir noticia">${safeImage(lead.image_url)?`<img src="${escapeHtml(safeImage(lead.image_url))}" alt="${escapeHtml(lead.title)}" loading="eager">`:'<div class="featured-placeholder">ALBA · NOTICIAS</div>'}</button><div class="featured-content"><div class="card-meta"><span class="tag">${escapeHtml(lead.category)}</span><span class="source-tag">${escapeHtml(lead.source)}</span></div><h2>${escapeHtml(lead.title)}</h2><p>${escapeHtml(albaInsights(lead).summary)}</p><div class="featured-meta">${escapeHtml(formatDate(lead.published_at))}</div><button class="featured-link article-open" data-id="${escapeHtml(lead.id)}" type="button">Leer análisis ALBA →</button></div></article>`:'';}
  const cards=items.slice(featured&&items.length?1:0);
  if(grid)grid.innerHTML=cards.map(n=>`<article class="card"><button class="card-image-wrap article-open" data-id="${escapeHtml(n.id)}" type="button" aria-label="Abrir noticia">${safeImage(n.image_url)?`<img class="card-image" src="${escapeHtml(safeImage(n.image_url))}" alt="${escapeHtml(n.title)}" loading="lazy">`:'<div class="card-image placeholder">ALBA · NOTICIAS</div>'}</button><div class="card-body"><div class="card-meta"><span class="tag">${escapeHtml(n.category)}</span><span class="source-tag">${escapeHtml(n.source)}</span></div><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(albaInsights(n).summary)}</p><div class="card-footer"><time>${escapeHtml(formatDate(n.published_at))}</time><button class="read-more article-open" data-id="${escapeHtml(n.id)}" type="button">Ver análisis →</button></div></div></article>`).join('');
  if(empty){empty.hidden=items.length>0;empty.textContent=items.length?'':(q||activeCategory!=='Todas'||activeSource!=='Todas'?'No encontramos noticias con esos filtros.':'No encontramos noticias disponibles.');}
 };
 const bindFilter=(container,setter)=>container?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;setter(b.dataset.value||'Todas');container.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});
 const renderFilters=()=>{if(filters)filters.innerHTML=['Todas',...new Set(categories)].map(c=>`<button type="button" class="filter ${c==='Todas'?'active':''}" data-value="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');if(sourceFilters)sourceFilters.innerHTML=['Todas',...new Set(sources)].map(s=>`<button type="button" class="filter ${s==='Todas'?'active':''}" data-value="${escapeHtml(s)}">${escapeHtml(s)}</button>`).join('')};
 const loadNews=async()=>{try{if(grid)grid.innerHTML='<p class="empty">Cargando noticias…</p>';if(liveStatus)liveStatus.textContent='Conectando con la actualidad…';categories=[...fallbackCategories];sources=[...fallbackSources];renderFilters();const headers={apikey:ALBA_SUPABASE_KEY,Authorization:`Bearer ${ALBA_SUPABASE_KEY}`},base=`${ALBA_SUPABASE_URL}/rest/v1/`;const url=(table,params)=>{const u=new URL(base+table);Object.entries(params||{}).forEach(([k,v])=>u.searchParams.set(k,v));return u};const [ar,cr,sr]=await Promise.all([fetch(url('articles',{select:'id,title,summary,content,image_url,published_at,category_id,source_id,metadata',status:'eq.published',order:'published_at.desc.nullslast',limit:'100'}),{headers,cache:'no-store'}),fetch(url('categories',{select:'id,name',is_active:'eq.true',order:'name.asc',limit:'100'}),{headers,cache:'no-store'}),fetch(url('sources',{select:'id,name',is_active:'eq.true',order:'name.asc',limit:'100'}),{headers,cache:'no-store'})]);if(!ar.ok)throw new Error(`Noticias ${ar.status}`);const ad=await ar.json(),cd=cr.ok?await cr.json():[],sd=sr.ok?await sr.json():[],cm=new Map(cd.map(x=>[x.id,x.name])),sm=new Map(sd.map(x=>[x.id,x.name]));news=ad.map(n=>({...n,category:cm.get(n.category_id)||'Actualidad',source:sm.get(n.source_id)||'Fuente desconocida'}));categories=[...new Set([...fallbackCategories,...cd.map(x=>x.name).filter(Boolean),...news.map(x=>x.category)])];sources=[...new Set([...fallbackSources,...sd.map(x=>x.name).filter(Boolean),...news.map(x=>x.source)])];renderFilters();render();const now=new Date().toLocaleTimeString('es-HN',{hour:'2-digit',minute:'2-digit'});if(lastUpdated)lastUpdated.textContent=`Última actualización: ${now}`;if(liveStatus)liveStatus.textContent='Conectado · actualización automática activa'}catch(e){console.error('ALBA',e);if(liveStatus)liveStatus.textContent='Conexión temporalmente limitada';news=[];renderFilters();if(featured)featured.innerHTML='';if(grid)grid.innerHTML='';if(empty){empty.hidden=false;empty.textContent='No se pudieron cargar las noticias en este momento. Estamos revisando la conexión con ALBA.'}}};
 grid?.addEventListener('click',e=>{const b=e.target.closest('.article-open');if(!b)return;const n=news.find(x=>String(x.id)===String(b.dataset.id));if(n)openArticle(n)});featured?.addEventListener('click',e=>{const b=e.target.closest('.article-open');if(!b)return;const n=news.find(x=>String(x.id)===String(b.dataset.id));if(n)openArticle(n)});
 bindFilter(filters,v=>activeCategory=v);bindFilter(sourceFilters,v=>activeSource=v);input?.addEventListener('input',render);document.getElementById('searchToggle')?.addEventListener('click',()=>{searchBar.classList.add('open');input?.focus()});document.getElementById('searchClose')?.addEventListener('click',()=>{searchBar.classList.remove('open');if(input)input.value='';render()});
 loadNews();
 setInterval(loadNews,300000);
});